#:schema node_modules/wrangler/config-schema.json
name = "my-todo-app-z07"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Next.js Pages-д зориулсан гаралт (.vercel/output/static-ыг ашиглах нь найдвартай)
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ochkotodo"
database_id = "3c5067ad-b7a3-45c2-abf8-9e2c135c49ae"